SurveyOn/SurveyOn.Front/Controllers/SurveyController.cs
using System;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using SurveyOn.Dto;
using SurveyOn.Front.Filters;

namespace SurveyOn.Front.Controllers
{
    public class SurveyController : Controller
    {
        public ActionResult Index()
        {
            return RedirectToAction("Login");
        }

        [Route("login")]
        public ActionResult Login()
        {
            return View();
        }

        [HttpPost, Route("authenticate")]
        public HttpStatusCodeResult Authenticate(UserDto dto)
        { 
            var authTicket = new FormsAuthenticationTicket(
                1,
                dto.Email,
                DateTime.Now,
                DateTime.Now.AddHours(24),
                false,
                ""
            );

            var encryptedTicket = FormsAuthentication.Encrypt(authTicket);

            var authCookie = new HttpCookie(FormsAuthentication.FormsCookieName, encryptedTicket);
            HttpContext.Response.Cookies.Add(authCookie);

            return new HttpStatusCodeResult(HttpStatusCode.NoContent);
        }
        [SimpleAuthorization]
        [Route("edit/{surveyId}")]
        public ActionResult Edit(int surveyId)
        {
            return View();
        }
        
        [SimpleAuthorization]
        [Route("home")]
        public ActionResult Home()
        {
            return View();
        }

        [Route("test")]
        public ActionResult tempQuestionTypes()
        {
            return View();
        }

        [Route("register")]
        public ActionResult Register()
        {
            return View();
        }

        [Route("unauthorized", Name = "Unauthorized")]
        public ActionResult Unauthorized()
        {
            return View();
        }

        [Route("complete/{surveyId}")]
        public ActionResult Complete(int surveyId)
        {
            return View();
        }

        [Route("review/{surveyId}")]
        public ActionResult Review(int surveyId)
        {
            return View();
        }

        [Route("confirmation")]
        public ActionResult AnswerConfirmation()
        {
            return View();
        }
    }
}

SurveyOn/SurveyOn.Front/Views/Shared/_LayoutCompleteSurvey.cshtml
<!DOCTYPE html>

<html>
<head>
    <link rel="shortcut icon" type="image/x-icon" href="~/Content/Images/favicons/favicon.ico" />

    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" href="~/Content/Libs/bootstrap.min.css" />
    <link rel="stylesheet" href="~/Content/Libs/font-awesome.min.css" />
    <link rel="stylesheet" href="~/Content/home.css" />
    <link rel="stylesheet" href="~/Content/Libs/bootstrap-datetimepicker.min.css" />
    <link rel="stylesheet" href="~/Content/Libs/bootstrap-toggle.min.css" />

    <script src="~/Scripts/Libs/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/Libs/bootstrap.min.js"></script>
    <script src="~/Scripts/Libs/knockout-3.4.0.js"></script>
    <script src="~/Scripts/Libs/moment-with-locales.min.js"></script>
    <script src="~/Scripts/Libs/bootstrap-datetimepicker.min.js"></script>
    <script src="~/Scripts/Libs/bootstrap-toggle.min.js"></script>
    <script src="~/Scripts/Libs/expanding.js"></script>
    <script src="~/Scripts/Libs/extensions/knockoutExtension.js"></script>
</head>
<body>
    <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="row">
                <div class="col-xs-1 visible-xs">&nbsp;</div>
                <div class="navbar-brand col-xs-5 col-sm-7 logo">
                    <a href="/home" class="navbar-link"><img src="~/Content/Images/logo.png" alt="SurveyOn" style="height: 100%"/></a>
                </div>
                <div class="col-xs-3 col-sm-5">
                    <div class="navbar-right">
                        <div class="navbar-nav">
                            <a href="/login" class="navbar-link navbar-brand" id="login"><i class="fa fa-sign-in fa-lg" data-toggle="tooltip" data-placement="bottom" title="Log in"></i></a>
                        </div>
                    </div>
                </div>
                <div class="col-xs-1 visible-xs">&nbsp;</div>
            </div>
        </div>
    </nav>
    <div class="container">
        @RenderBody()
    </div>
    <script src="~/Scripts/enums.js"></script>
    <script src="~/Scripts/ajaxHelper.js"></script>
    <script src="~/Scripts/utilityApplier.js"></script>
    @RenderSection("Scripts", false)
<script>
    $(document).ready(function() {
         surveyOn.utilityApplier.apply.tooltips();
    });
</script>
</body>
</html>

SurveyOn/SurveyOn.Front/Views/Shared/_LayoutHome.cshtml
<!DOCTYPE html>

<html>
<head>    
    <link rel="shortcut icon" type="image/x-icon" href="~/Content/Images/favicons/favicon.ico" />

    <meta name="viewport" content="width=device-width"/>
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" href="~/Content/section.css"/>
    <link rel="stylesheet" href="~/Content/Libs/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/Content/Libs/font-awesome.min.css"/>
    <link rel="stylesheet" href="~/Content/home.css"/>
    <link rel="stylesheet" href="~/Content/question.css"/>
    <link rel="stylesheet" href="~/Content/popover.css"/>
    <link rel="stylesheet" href="~/Content/Libs/bootstrap-datetimepicker.min.css"/>
    <link rel="stylesheet" href="~/Content/Libs/bootstrap-toggle.min.css"/>
    <link rel="stylesheet" href="~/Content/Libs/dataTables.bootstrap.min.css"/>
    <link rel="stylesheet" href="~/Content/Libs/buttons.bootstrap.min.css"/>

    <script src="~/Scripts/Libs/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/Libs/bootstrap.min.js"></script>
    <script src="~/Scripts/Libs/knockout-3.4.0.js"></script>
    <script src="~/Scripts/Libs/moment-with-locales.min.js"></script>
    <script src="~/Scripts/Libs/bootstrap-datetimepicker.min.js"></script>
    <script src="~/Scripts/Libs/bootstrap-toggle.min.js"></script>
    <script src="~/Scripts/Libs/expanding.js"></script>
    <script src="~/Scripts/Libs/knockstrap.js"></script>
    <script src="~/Scripts/Libs/extensions/knockoutExtension.js"></script>
    <script src="~/Scripts/Libs/jquery.dataTables.min.js"></script>
    <script src="~/Scripts/Libs/dataTables.bootstrap.min.js"></script>
</head>
<body>
    <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="row">
                <div class="col-xs-1 visible-xs">&nbsp;</div>
                <div class="navbar-brand col-xs-5 col-sm-6 logo"><a href="/home" class="navbar-link"><img src="~/Content/Images/logo.png" alt="SurveyOn" style="height: 100%"/></a>
                </div>
                <div class="relative col-xs-1">
                    <!-- ko if: $data.hasOwnProperty('surveys') && surveys().length == 0 -->
                    <div class="add-survey-helper">
                        <i class="fa fa-3x fa-share" aria-hidden="true"></i>
                        <div class="tooltip fade bottom in" role="tooltip" style="right: -23px; top: 40px;">
                            <div class="tooltip-arrow"></div>
                            <div class="tooltip-inner">Click to add survey!</div>
                        </div>
                    </div>
                    <!-- /ko -->
                    <div class="navbar-brand">
                        <a href="#" id="addSurvey" data-toggle="tooltip" data-placement="bottom" title="Add survey" class="navbar-link"><i class="fa fa-plus-square-o fa-lg"></i></a>
                    </div>
                </div>
                <div class="col-xs-3 col-sm-5">
                    <div class="navbar-right">
                        <div class="navbar-nav">
                            <a href="#" class="navbar-link"><img class="gravatar img-rounded" data-toggle="tooltip" data-placement="left" /></a>
                            <a id="logout" class="navbar-link navbar-brand" href="#"><i class="fa fa-power-off fa-lg" data-toggle="tooltip" data-placement="bottom" title="Log out"></i></a>
                        </div>
                    </div>
                </div>
                <div class="col-xs-1 visible-xs">&nbsp;</div>
            </div>
        </div>
    </nav>
    <div class="container">
        @RenderBody()
    </div>
    <script src="~/Scripts/enums.js"></script>
    <script src="~/Scripts/updateHelper.js"></script>
    <script src="~/Scripts/ajaxHelper.js"></script>
    <script src="~/Scripts/utilityApplier.js"></script>
    @RenderSection("Scripts", false)
    <script>
        $('.gravatar').attr('title', sessionStorage.getItem('email'));
        $(document)
            .ready(function () {
                if (typeof (Storage) !== "undefined") {
                    var uri = "/api/users?email=" + sessionStorage.getItem('email');
                    if (!sessionStorage.getItem('gravatarUrl') || !sessionStorage.getItem('userId')) {
                        surveyOn.ajaxHelper.request(
                            uri,
                            'GET',
                            null,
                            function (response) {
                                var url = "https://www.gravatar.com/avatar/";
                                sessionStorage.setItem('gravatarUrl', url + response.EmailHash + "?s=45");
                                $('.gravatar').attr('src', sessionStorage.getItem('gravatarUrl'));
                                sessionStorage.setItem('userId', response.Id);
                            });
                    } else {
                        $('.gravatar').attr('src', sessionStorage.getItem('gravatarUrl'));

                    }
                } else {
                    $('.gravatar').attr('src', "https://www.gravatar.com/avatar/?s=45");
                    $('.gravatar').attr('title', "Error");
                }

                $('#addSurvey')
                    .click(function(event) {
                        event.preventDefault();
                        surveyOn.ajaxHelper.request(
                            '/api/surveys',
                            'POST',
                            null,
                            function(response) {
                                window.location.replace('/edit/' + response.Id);
                            });
                    });

            $('#logout')
                .click(function(event) {
                    event.preventDefault();
                    surveyOn.utilityApplier.apply.clearCookies();
                    sessionStorage.clear();
                    window.location.replace("/login");
                });

            surveyOn.utilityApplier.apply.tooltips();
        });
</script>
</body>
</html>

SurveyOn/SurveyOn.Front/Views/Shared/_LayoutLogin.cshtml
<!DOCTYPE html>

<html>
<head>
    <link rel="shortcut icon" type="image/x-icon" href="~/Content/Images/favicons/favicon.ico" />
    
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" href="~/Content/Libs/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/Content/Libs/font-awesome.min.css"/>
    <link rel="stylesheet" href="~/Content/login.css"/>

    <script src="~/Scripts/Libs/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/Libs/knockout-3.4.0.js"></script>
    <script src="~/Scripts/Libs/bootstrap.min.js"></script>
    <script src="~/Scripts/Libs/knockout-3.4.0.js"></script>
</head>
<body>
<div class="flex-container">
    <div class="well">
        <div class="text-center"><img src="~/Content/Images/logo.png" alt="SurveyOn" style="height: 80px;" /></div>
        @RenderBody()
    </div>
</div>
    <script src="~/Scripts/ajaxHelper.js"></script>
    <script src="~/Scripts/utilityApplier.js"></script>
    @RenderSection("Scripts", false)
</body>
</html>

SurveyOn/SurveyOn.Front/Views/Survey/AnswerConfirmation.cshtml
@{
    ViewBag.Title = "AnswerConfirmation";
    Layout = "~/Views/Shared/_LayoutLogin.cshtml";
}

<div class="text-center">
    <h1>Thank You for completing the survey!</h1>
    <p>To create your own surveys <a href="/register">create an account.</a></p>
    <p>Or <a href="/login">log in.</a></p>
</div>

SurveyOn/SurveyOn.Front/Views/Survey/Complete.cshtml
@{
    ViewBag.Title = "Complete";
    Layout = "~/Views/Shared/_LayoutCompleteSurvey.cshtml";
}

<form data-bind="submit: fillAnswersArray">
    <div class="text-center" data-bind="with: survey">
        <h1 class="wrap" data-bind="text: title"></h1>
        <p data-bind="text: description" class="text-justify wrap"></p>
        <div data-bind="foreach: sections">
            <div class="well text-justify section-well">
                <h3 data-bind="text: title" class="wrap"></h3>
                <p data-bind="text: description" class="text-justify wrap"></p>
                <div data-bind="foreach: questions">
                    <div class="well">
                        <div class="question-title-container">
                            <!-- ko if: required -->
                            <div class="exclamation-container"><i class="fa fa-exclamation-circle fa-lg" data-toggle="tooltip" title="Required!" data-placement="left"></i></div>
                            <!-- /ko -->
                            <h4 class="question-title wrap" data-bind="text: title"></h4>
                        </div>
                        <p data-bind="text: description" class="text-justify wrap"></p>
                        <!-- ko if: questionType() == 1 -->
                        <div class="answer-container">
                            <input class="form-control answer" placeholder="Short answer here" data-bind="value: answer, isrequired: required" maxlength="128" 
                                   oninvalid="{ this.setCustomValidity('This question is required'); jQuery(this).parents('div.answer-container').addClass('has-error');}" 
                                   oninput="{ this.setCustomValidity(''); jQuery(this).parents('div.has-error').removeClass('has-error');}" />
                        </div>
                        <!-- /ko -->
                        <!-- ko if: questionType() == 2 -->
                        <div class="answer-container">
                            <textarea class="form-control expanding answer" rows="1" placeholder="Long answer here" data-bind="value: answer, isrequired: required" maxlength="512" 
                                      oninvalid="{ this.setCustomValidity('This question is required'); jQuery(this).parents('div.answer-container').addClass('has-error'); }" 
                                      oninput="{ this.setCustomValidity(''); jQuery(this).parents('div.has-error').removeClass('has-error'); }"></textarea>
                        </div>
                        <!-- /ko -->
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- ko if: published -->
    <button type="submit" class="btn btn-lg btn-success pull-right submit-button"><i class="fa fa-check" aria-hidden="true"></i> Submit</button>
    <!-- /ko -->
</form>

@section Scripts{
    <script src="~/Scripts/questionViewModel.js"></script>
    <script src="~/Scripts/sectionViewModel.js"></script>
    <script src="~/Scripts/surveyViewModel.js"></script>
    <script src="~/Scripts/answer.js"></script>
    <script src="~/Scripts/utilityApplier.js"></script>
    <script src="~/Scripts/completeSurveyViewModel.js"></script>
}

SurveyOn/SurveyOn.Front/Views/Survey/Edit.cshtml
@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_LayoutHome.cshtml";
}

<div class="text-center" data-bind="with: survey">
    <!-- ko if: sections().length == 0 -->
    <div class="add-section-helper">
        <i class="fa fa-3x fa-share" aria-hidden="true"></i>
        <div class="tooltip fade bottom in" role="tooltip" style="right: -23px; top: 40px;">
            <div class="tooltip-arrow"></div>
            <div class="tooltip-inner">Click to add section!</div>
        </div>
    </div>
    <!-- /ko -->
    <div class="add-section" data-toggle="tooltip" data-placement="top" data-trigger="hover" title="Add section">
        <a href="#" data-bind="click: addSection"><i class="fa fa-sticky-note-o fa-2x"></i></a>
    </div>

    <div class="modal" id="confirm-publish-survey-modal" tabindex="-1">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">Published survey adress</h4>
                </div>
                <div class="modal-body">
                    <div class="input-group">
                        <input id="published-modal-complete-input" class="form-control" data-bind="value: $root.publishedSurveyUrl" />
                        <span class="input-group-btn">
                            <button type="button" class="btn btn-default" data-toggle="tooltip" title="Copy to clipboard" data-bind="click: $root.copyCompliteUrlToClipboard">
                                <i class="fa fa-clipboard"></i>
                            </button>
                        </span>
                    </div>
                </div>
                <div class="modal-footer">
                    @*<button class="fa fa-times fa-2x pull-right question-bar-element question-bar-button" data-toggle="tooltip" title="Close" data-dismiss="modal"></button>*@
                    <button class="fa fa-external-link fa-2x pull-right question-bar-element question-bar-button" data-toggle="tooltip" title="Go to published survey" data-bind="click: $root.goToPublishedSurvey"></button>
                </div>
            </div>isPublished
        </div>
    </div>

    <div class="row">

        <div class="col-xs-10">
            <input class="survey-title" placeholder="Title" data-bind="value: title" maxlength="128" />
        </div>
        <div class="col-xs-2">
            <div data-toggle="tooltip" data-placement="bottom" data-trigger="hover" title="Go to answers">
                <a id="review" data-bind="attr: {'href': '/review/' + id()}">
                    <i class="fa fa-table fa-3x question-bar-button question-bar-icons"></i>
                </a>
            </div>
            <div class="section-settings-icon" data-toggle="tooltip" title="Survey settings">
                <button class="fa fa-cog fa-lg fa-2x question-bar-button" data-bind="popover: {
                    options: {trigger: 'focus', title: '', placement: 'bottom'},
                    template: $root.surveySettingsPopoverContent,
                    data: { text: 'First template' }
                    }, click : surveyOn.utilityApplier.apply.tooltips()"></button>
            </div>
            <script type="text/html" id="survey-settings-popover-content">
                <div align="center">
                    <div data-toggle="tooltip" title="Publish?" class="onoffswitch switch-tooltip popover-element-left">
                        <input type="checkbox" class="onoffswitch-checkbox" data-bind="checked: $parent.isPublished, attr: { id:  $parent.id}">
                        <label class="onoffswitch-label" data-bind="attr: {for:  $parent.id}">
                            <span class="onoffswitch-inner"></span>
                            <span class="onoffswitch-switch"></span>
                        </label>
                    </div>
                    @*<input type="checkbox" data-bind="checked: $parent.isPublished" data-toggle="tooltip" data-placement="right" title="Publish" />*@
                    <!-- ko if: $root.survey().isPublished() == true -->
                    <button class="fa fa-external-link fa-2x popover-element popover-button " data-toggle="tooltip" title="Go to published survey" data-bind="click: $root.goToPublishedSurvey"></button>
                    <!-- /ko -->
                </div>
            </script>
        </div>
    </div>
    <div>
        <textarea class="survey-description expanding" placeholder="Description" data-bind="value: description" maxlength="512"></textarea>
    </div>

    <div class="modal" id="confirm-delete-section-modal" tabindex="-1">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">Delete section confirmation</h4>
                </div>
                <div class="modal-body">
                    <span>Are you sure you want to delete section with <span data-bind="text: $root.numberOfQuestionsInRemovingSection"></span> question/s?</span>
                </div>
                <div class="modal-footer">
                    @*                    <button class="fa fa-times fa-2x question-bar-element pull-right question-bar-button" data-toggle="tooltip" title="Close" data-dismiss="modal"></button>*@
                    <button class="fa fa-check fa-2x question-bar-element pull-right question-bar-button" data-toggle="tooltip" title="Confirm" data-bind="click: $root.removeSection"></button>
                </div>
            </div>
        </div>
    </div>

    <div data-bind="foreach: sections">
        <div class="well section-container">
            <div class="section-settings-icon " data-toggle="tooltip" title="Section settings">
                <button class="fa fa-cog fa-lg fa-2x question-bar-button" data-bind="popover: {
                    options: {trigger: 'focus', title: '', placement: 'bottom'},
                    template: $root.sectionSettingsPopoverContent,
                    data: { text: 'First template' }
                    }, click : surveyOn.utilityApplier.apply.tooltips()"></button>
            </div>
            <script type="text/html" id="section-settings-popover-content">
                <button class="fa fa-trash fa-2x popover-button" data-toggle="tooltip" data-placement="right" title="Remove section" data-bind="click: $root.removeSectionConfirmation.bind($data, $parent)"></button>
            </script>

            <div class="section-title-container">
                <input class="section-title" placeholder="Section title" data-bind="value: title" maxlength="128" />
            </div>
            <div class="section-description-container">
                <textarea class="section-description expanding" placeholder="Section description" data-bind="value: description" maxlength="512"></textarea>
            </div>
            <div data-bind="foreach: questions">
                <div class="well question-container">
                    <div class="move-up-arrow-container" hidden>
                        <i class="fa fa-arrow-up question-up-arrow-icon" data-toggle="tooltip" title="Move up" data-placement="right"></i>
                    </div>
                    <div class="question-specification-container col-xs-12">
                        <div class="question-required-icon-container col-xs-1">
                            <i class="fa fa-exclamation-circle fa-2x fa-pull-left" data-bind="visible: required" data-toggle="tooltip" title="Required!" data-placement="left"></i>
                        </div>
                        <div class="question-title-container col-xs-9">
                            <input class="question-title pull-left col-xs-12" placeholder="Question title" data-bind="value: title" maxlength="128" />
                        </div>
                        <div class="dropdown-menu-right question-dropdown-select pull-right col-xs-2" data-toggle="tooltip" data-placement="bottom" title="Question type selector">
                            <select class="form-control" data-bind="options: questionTypes, optionsText: 'name', optionsValue: 'id', value: questionType, event: {change: updateQuestionType}"></select>
                        </div>
                        <div class="question-description-container col-xs-12 pull-left">
                            <textarea class="question-description col-xs-10 expanding" placeholder="Question description" data-bind="value: description" maxlength="512"></textarea>
                        </div>
                    </div>
                    <div class="question-answer-container pull-left col-xs-12">
                        <!-- ko if: questionType() == 1 -->
                        <div class="question-short-answer  pull-left col-xs-12">
                            <input class="form-control shortAnswer" placeholder="Short answer here" disabled />
                        </div>
                        <!-- /ko -->
                        <!-- ko if: questionType() == 2 -->
                        <div class="question-long-container pull-left col-xs-12">
                            <textarea class="form-control expanding long-Answer" rows="1" placeholder="Long answer here" disabled></textarea>
                        </div>
                        <!-- /ko -->
                    </div>
                    <div class="question-toolbar-container">
                        <div class="col-xs-12">
                            <div class="question-toolbar-separator"></div>
                        </div>
                        <div class="question-bar-icons col-xs-12">
                            <div data-toggle="tooltip" title="Is required?" class="onoffswitch question-bar-icons pull-left switch-tooltip">
                                <input type="checkbox" name="onoffswitch" class="onoffswitch-checkbox" data-bind="checked: required, attr: { id: id}">
                                <label class="onoffswitch-label" data-bind="attr: {for: id}">
                                    <span class="onoffswitch-inner"></span>
                                    <span class="onoffswitch-switch"></span>
                                </label>
                            </div>
                            <button class="fa fa-picture-o fa-2x question-bar-element pull-left question-bar-button hidden-icon" data-toggle="tooltip" title="Add picture"></button>
                            <button class="fa fa-eyedropper fa-2x question-bar-element pull-left question-bar-button hidden-icon" data-toggle="tooltip" title="Change color"></button>
                            <button class="fa fa-file-o fa-2x question-bar-element pull-left question-bar-button hidden-icon" data-toggle="tooltip" title="Duplicate"></button>
                            <button class="fa fa-trash pull-right fa-2x question-bar-element question-bar-button" data-toggle="tooltip" title="Remove question" data-bind="click: $parent.removeQuestion"></button>
                        </div>
                    </div>
                    <div class="move-down-arrow-container" hidden>
                        <i class="fa fa-arrow-down right-navbar-down-icon question-down-arrow-icon" data-toggle="tooltip" data-placement="right" title="Move down"></i>
                    </div>
                </div>
            </div>
            <div hidden>
                <i class="fa fa-arrow-circle-o-down fa-2x section-down-arrow-icon"></i>
            </div>
            <div class="relative">
                <button class="fa fa-trash pull-right fa-2x question-bar-button hidden-icon" data-toggle="tooltip" title="Remove section" data-bind="click: $root.removeSectionConfirmation.bind($data, $parent)"></button>
                <!-- ko if: questions().length == 0 -->
                <div class="add-question-helper">
                    <i class="fa fa-3x fa-share" aria-hidden="true"></i>
                    <div class="tooltip fade bottom in" role="tooltip" style="right: -23px; top: 40px;">
                        <div class="tooltip-arrow"></div>
                        <div class="tooltip-inner">Click to add question!</div>
                    </div>
                </div>
                <!-- /ko -->
                <button class="btn btn-default pull-right add-question question-bar-button" data-bind="click: addQuestion" data-toggle="tooltip" title="Add question"><i class="fa fa-plus fa-2x"></i></button>
            </div>
        </div>
    </div>
</div>

@section Scripts{
    <script src="~/Scripts/questionViewModel.js"></script>
    <script src="~/Scripts/sectionViewModel.js"></script>
    <script src="~/Scripts/surveyViewModel.js"></script>
    <script src="~/Scripts/editViewModel.js"></script>
    <script src="~/Scripts/Libs/expanding.js"></script>
}

SurveyOn/SurveyOn.Front/Views/Survey/Login.cshtml

@{
    ViewBag.Title = "Log In";
    Layout = "~/Views/Shared/_LayoutLogin.cshtml";
}

<div>
    <h1 align="center"> Welcome to SurveyOn!</h1>
    <div align="center">
        
        <form class="center-group form-horizontal" data-bind="submit: login">
            <div class="form-group row">
                <div class="col-xs-offset-1 col-xs-1">
                    <i class="fa fa-at fa-2x input-icon"></i>
                </div>
                <div class="col-xs-8 ">
                    <input class="form-control" type="email" data-bind="value: emailAddress" placeholder="Email Adress" required>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-xs-offset-1 col-xs-1">
                    <i class="fa fa-hashtag fa-2x"></i>
                </div>
                <div class="col-xs-8 ">
                    <input class="form-control" type="password" data-bind="value: password" placeholder="Password" />
                </div>
            </div>
            <div class="errPopup" hidden> Wrong Email or password! </div>
            <div align="center" class="submit">
                <button type="submit" class="btn btn-info">
                    <i class="fa fa-home fa-lg"></i> Log In
                </button>
            </div>
        </form>
    </div>
    <p>
        <div style="width: 50%; margin: auto">
            <div style="width: 100%; height: 1px; background-color: #222; margin: 15px 0 15px 0"></div>   
        </div>
        <div class="w3-container w3-border-top w3-color-black" align="center">
            Or <a href="@Url.Action("Register", "Survey")" class="btn btn-info" role="button">
                <i class="fa fa-user-plus fa-lg"></i> Register
            </a> to create a new account!
        </div>
    </p>
</div>
@section Scripts{
    <script src="~/Scripts/loginViewModel.js"></script>
}

SurveyOn/SurveyOn.Front/Views/Survey/Unauthorized.cshtml
@{
    ViewBag.Title = "Unauthorized";
    Layout = "~/Views/Shared/_LayoutLogin.cshtml";
}

<div class="text-center">
    <h1>Unauthorized</h1>
    <p>We are sorry, but you do not have permission to access this page!</p>
    <p><a href="/login">Proceed to login page.</a></p>
</div>